apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config-map
data:
  APP_NAME: Laravel
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: http://localhost:8000

  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug

  DB_CONNECTION: mysql
  #APP_KEY: base64:7pQYfcBpJB/A4ehSf9ScYEfk8CukvZtVu5OJDhonyDw=
  # DB_HOST: mysql-service
  # DB_PORT: "3306"
  # DB_DATABASE: elearning
  # DB_USERNAME: islem
  # DB_PASSWORD: "28225822"

  BROADCAST_DRIVER: reverb
  CACHE_DRIVER: file
  FILESYSTEM_DRIVER: local
  QUEUE_CONNECTION: redis
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"

  MEMCACHED_HOST: 127.0.0.1

  REDIS_HOST: redis-service
  #REDIS_PASSWORD: 
  REDIS_PORT: "6379"

  MAIL_MAILER: smtp
  MAIL_HOST: elearning-web-app-mailhog-1
  MAIL_PORT: "1025"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: islem@el.com
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  PUSHER_APP_ID: aaa
  PUSHER_APP_KEY: aaa
  PUSHER_APP_SECRET: aaa
  PUSHER_APP_CLUSTER: mt1

  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
  URL_SIGNER_SIGNATURE_KEY: some_random_value

  DO_KEY: ""

  DO_ACCESS_KEY_ID: ""
  DO_SECRET_ACCESS_KEY: ""
  DO_DEFAULT_REGION: ""
  DO_BUCKET: ""
  DO_FOLDER: ""
  DO_CDN_ENDPOINT: ""
  DO_ENDPOINT: ""
  DO_USE_PATH_STYLE_ENDPOINT: "false"

  DATA_PATH_HOST: .
  WEB_SOCKET_PORT: "80"
  REVERB_APP_ID: aaa
  REVERB_APP_KEY: aaa
  REVERB_APP_SECRET: aaa
  REVERB_HOST: websocket-service
  REVERB_PORT: "80"
  REVERB_SCHEME: http
  WEB_SOCKET_HOST: websocket-service
  REVERB_SERVER_HOST: 0.0.0.0
  REVERB_SERVER_PORT: "6001"
  VITE_REVERB_APP_KEY: aaa
  VITE_REVERB_HOST: localhost
  VITE_REVERB_PORT: "80"
