apiVersion: v1
kind: Secret
metadata:
  name: php-secret
type: Opaque
stringData:
    APP_KEY: base64:7pQYfcBpJB/A4ehSf9ScYEfk8CukvZtVu5OJDhonyDw=
    DB_HOST: mysql-service
    DB_PORT: "3306"
    DB_DATABASE: elearning
    DB_USERNAME: username
    DB_PASSWORD: password

  
